# Generated by Django 4.1.5 on 2023-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_booking_delete_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boys',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'boys',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'information',
            },
        ),
    ]
